name: Compile Lua Mod
on:
  release:
    types:
      - created
  push:
  pull_request:

permissions:
  contents: write
  id-token: write
  pages: write

jobs:
  lint-and-compile:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4.6.0
        with:
          python-version: "3.10"
      - run: pip install https://github.com/justalemon/Collei/archive/master.zip
      - run: python -m collei natives fivem.lua cfxlua --lists gtav fivem
      - uses: lunarmodules/luacheck@v1.1.0
      - run: rm -r dist/simplepassive || true && mkdir -p dist/simplepassive && cp *.lua dist/simplepassive
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}
          path: dist
  deploy:
    runs-on: ubuntu-22.04
    needs:
      - lint-and-compile
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: ${{ github.event.repository.name }}
          path: dist
      - run: 7z a ${{ github.event.repository.name }}.zip ${{ github.workspace }}/dist/*
      - run: ls -R
        working-directory: dist